### ISSUE TITLE
a melpa-package?

### ISSUE THREAD

**Issue by ArneBab** [mmitch/ox-bb#2]
Hi,

Is it planned to [submit a melpa package](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)? This would make it much easier to use the exporter.

Best wishes,
Arne

**Comment by mmitch** [comment]
To be honest, I don't have anything planned for this project:  I wrote it to make a single elaborated post in a web forum and have not used it since then ;-)

Would you also be OK with an inclusion in the org core instead of a separate melpa package?

I already have one plugin accepted and included in the org core (and thus in emacs itself) – I could offer this exporter to the org project as well.
I'd probably have to rewrite the shell test script into elisp and the code review process might take some iterations.
All in all it will take some time but it should be possible.

If org is not interested in the exporter, I could still create a melpa package.

What do you think?

**Comment by ArneBab** [comment]
Thank you for your answer!

Inclusion in org core would be even nicer! I didn’t dare to ask for that :-)

The need arose for myself, because I’m sometimes writing forum answers that I would also like to publish in other formats. Writing them directly in org-mode allows me to publish them on my website (it’s built on org publish) and still get them into the Forum without much hassle.

**Comment by mmitch** [comment]
Status update:
I'm on it, but it turns into a bit of yak-shaving :-)

* The initial post to the orgmode-ml is done. I think you were the only person to answer as of now.
* I stumbled about a bug in `test-org-archive/datetree` with German locale, which got me distracted.
* There is issue #3 which I have yet to report to the orgmode-ml. It introduces a regression that fails one of my tests. I'd rather like to fix it than to adapt my test to the IMHO buggy output.
* The patch for the inclusion of ox-bb is in preparation. Missing parts are the commit message (I have to look up the formatting rules again) and documentation updates. I have set up a local branch against the orgmode repo which includes ox-bb and passes the tests (apart from that issue #3).

**Comment by ArneBab** [comment]
Thank you for your update!

Please tell me if/how I can help with testing.

**Comment by mmitch** [comment]
I have submitted the patch, let's see what happens:
https://lists.gnu.org/archive/html/emacs-orgmode/2021-02/msg00063.html

**Comment by ArneBab** [comment]
Thank you!

**Comment by mmitch** [comment]
As Org does not respond, I'm going the MELPA route: https://github.com/melpa/melpa/pull/7434

**Comment by mmitch** [comment]
Well, that took about 20 minutes - we're on MELPA now :-)
I'll fix some code style issues and then release a version, so that we are also available in MELPA stable.

**Comment by ArneBab** [comment]
Christian Garbs <notifications@github.com> writes:

> Well, that took about 20 minutes - we're on MELPA now :-)
> I'll fix some code style issues and then release a version, so that we are also available in MELPA stable.

Nice!

Thank you!

Best wishes,
Arne
-- 
Unpolitisch sein
heißt politisch sein
ohne es zu merken

**Comment by mmitch** [comment]
v0.0.1 is now also released on MELPA stable.
We're all good!
